# Generated by Django 3.1.5 on 2021-03-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210322_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedback_1',
        ),
    ]
