# Generated by Django 3.1.5 on 2021-03-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210322_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_1',
        ),
    ]
