# Generated by Django 3.1.5 on 2021-03-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210322_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
